version: "3.9"

services:
  backend:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongodb:27017
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    volumes:
      - .data:/data
volumes:
  data:
